### ISSUE TITLE
Google collab notebook not found

### ISSUE THREAD

**Issue by Shubhamsk03** [LazyTurtle/DL-Project#1]

**Comment by LazyTurtle** [comment]
Did you have some problem opening the file [DL_Reidentification_Project.ipynb](https://github.com/LazyTurtle/DL-Reidentification/blob/main/DL_Reidentification_Project.ipynb)? I seem not to have problems on a private firefox window.

**Comment by LazyTurtle** [comment]
Did you have any problem opening the file [DL_Reidentification_Project.ipynb](https://github.com/LazyTurtle/DL-Reidentification/blob/main/DL_Reidentification_Project.ipynb)?
Using a private firefox window on a desktop I can see it perfectly.

**Comment by Shubhamsk03** [comment]
I have a problem opening the google collab of the same .

![Screenshot (55)](https://user-images.githubusercontent.com/89991346/232361777-e16262ca-7204-4b88-9667-2f60de0442c6.png)

**Comment by LazyTurtle** [comment]
Yeah sorry, I forgot to update the link when I renamed the project and files. It should work now.

**Comment by Shubhamsk03** [comment]
Thank you for your reply.
But still to run on the collab where should i upload the dataset.?
Can you please help me run it on a google team if possible at your
convenience?

Thanks and Regards,
Shubham S Kawalikai.

**Comment by LazyTurtle** [comment]
In the environment setup there is the variable `DATASET_DRIVE_PATH` there you have to insert the google drive path of the dataset. I could spare a few minutes to explain, just send me an email so that we can find a suitable date.

**Comment by Shubhamsk03** [comment]
Okay Thank you .
***@***.***
Looking forward to meeting you on a google meet.

**Comment by LazyTurtle** [comment]
Github do not allow sharing the email on these comments, contact me with the email on my github profile.

**Comment by Shubhamsk03** [comment]
Okay .
I have emailed you through the email on your github account.
